-- Seed: initial categories
insert into public.categories (name, slug, description, icon, color, sort_order) values
  ('AI Chat & Assistants',    'ai-chat',            'Conversational AI and chatbots',             '💬', '#6366f1', 1),
  ('Image Generation',        'image-generation',   'AI image and art generators',                '🎨', '#8b5cf6', 2),
  ('Writing & Copywriting',   'writing',            'AI writing assistants and copywriters',      '✍️', '#3b82f6', 3),
  ('Coding & Development',    'coding',             'AI coding assistants and code generators',   '💻', '#10b981', 4),
  ('Video Generation',        'video',              'AI video creation and editing tools',        '🎬', '#ef4444', 5),
  ('Audio & Music',           'audio',              'AI audio generation and music tools',        '🎵', '#f59e0b', 6),
  ('Productivity',            'productivity',       'AI tools to boost your productivity',        '⚡', '#06b6d4', 7),
  ('Business & Marketing',    'business',           'AI for business operations and marketing',   '💼', '#84cc16', 8),
  ('Education & Learning',    'education',          'AI tutors and educational tools',            '📚', '#f97316', 9),
  ('Design & UI',             'design',             'AI design tools and UI generators',          '🎭', '#ec4899', 10),
  ('Research & Analysis',     'research',           'AI research assistants and data analysis',   '🔬', '#0ea5e9', 11),
  ('SEO & Content',           'seo',                'AI tools for SEO and content strategy',      '📈', '#22c55e', 12),
  ('Voice & Speech',          'voice',              'AI voice synthesis and transcription',       '🎤', '#a855f7', 13),
  ('Data & Analytics',        'data-analytics',     'AI data analysis and visualization',         '📊', '#14b8a6', 14),
  ('Automation',              'automation',         'AI workflow and process automation',          '🤖', '#f43f5e', 15),
  ('Social Media',            'social-media',       'AI tools for social media management',       '📱', '#3b82f6', 16),
  ('Email & Communication',   'email',              'AI email and communication tools',           '📧', '#8b5cf6', 17),
  ('Legal & Compliance',      'legal',              'AI legal assistance and document tools',     '⚖️', '#6366f1', 18),
  ('Finance & Accounting',    'finance',            'AI finance and accounting tools',            '💰', '#10b981', 19),
  ('Healthcare & Medical',    'healthcare',         'AI tools for healthcare and medical use',    '🏥', '#ef4444', 20),
  ('HR & Recruitment',        'hr',                 'AI for HR and talent acquisition',           '👥', '#f59e0b', 21),
  ('Customer Support',        'customer-support',   'AI customer service and chatbots',           '🎧', '#06b6d4', 22),
  ('Translation',             'translation',        'AI translation and localization tools',      '🌐', '#84cc16', 23),
  ('Summarization',           'summarization',      'AI document and content summarizers',        '📝', '#f97316', 24),
  ('3D & Animation',          '3d-animation',       'AI 3D modeling and animation tools',         '🎮', '#ec4899', 25),
  ('Avatars & Personas',      'avatars',            'AI avatar and digital persona creators',     '👤', '#0ea5e9', 26),
  ('Presentations',           'presentations',      'AI presentation and slide makers',           '📊', '#22c55e', 27),
  ('E-commerce',              'ecommerce',          'AI tools for online stores and commerce',    '🛒', '#a855f7', 28),
  ('Search Engines',          'search',             'AI-powered search and discovery',            '🔍', '#14b8a6', 29),
  ('Life Assistant',          'life-assistant',     'Personal AI life and task assistants',       '🌟', '#f43f5e', 30),
  ('Dating & Social',         'dating-social',      'AI tools for social connections',            '❤️', '#3b82f6', 31),
  ('Fitness & Health',        'fitness',            'AI fitness and wellness tools',              '💪', '#8b5cf6', 32),
  ('Travel & Navigation',     'travel',             'AI travel planning and navigation',          '✈️', '#6366f1', 33),
  ('Food & Recipe',           'food',               'AI recipe and food recommendation tools',    '🍕', '#10b981', 34),
  ('Real Estate',             'real-estate',        'AI tools for real estate and property',      '🏠', '#ef4444', 35),
  ('Sports & Gaming',         'sports-gaming',      'AI for sports analytics and gaming',         '⚽', '#f59e0b', 36),
  ('News & Information',      'news',               'AI news aggregation and fact-checking',      '📰', '#06b6d4', 37),
  ('AI SuperTools',           'ai-supertools',      'The most powerful AI tools available',       '🚀', '#a855f7', 0),
  ('Verified Tools',          'verified',           'Reviewed and verified AI tools',             '✅', '#22c55e', 0),
  ('Free AI Tools',           'free-tools',         'Completely free AI tools',                   '🆓', '#84cc16', 0)
on conflict (slug) do nothing;
